CREATE TABLE `records` (
  `id` int(11) AUTO_INCREMENT NOT NULL,
  `name` varchar(128) NOT NULL,
  `artist` varchar(64) NOT NULL,
  `year` varchar(4) NOT NULL,
  `genre` varchar(64) NOT NULL,
  `no_of_disc` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `genres` (
  `id` int(11) AUTO_INCREMENT NOT NULL,
  `name` varchar(64) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `genres` VALUES
    (1,'Blues'),
    (2,'Jazz'),
    (3,'Rhythm and Blues'),
    (4,'Rock and Roll'),
    (5,'Rock'),
    (6,'Country'),
    (7,'Soul'),
    (8,'Dance'),
    (9,'Hip-Hop');


INSERT INTO records VALUES
    (1,'cursus purus. Nullam scelerisque neque sed sem','Ignatius Moreno',1966,'Soul',2),
    (2,'dui nec urna suscipit nonummy. Fusce fermentum','Samuel Valenzuela',1989,'Blues',4),
    (3,'luctus et ultrices posuere cubilia Curae Phasellus ornare.','Gemma Nelson',1997,'Rock and Roll',3),
    (4,'Morbi sit amet massa. Quisque porttitor eros nec tellus.','Deacon Moreno',1989,'Blues',1),
    (5,'quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus','Aubrey Baldwin',1978,'Rock and Roll',1),
    (6,'Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh.','Regan Warren',1999,'Jazz',3),
    (7,'lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus.','Len Richard',1964,'Jazz',3),
    (8,'eget laoreet posuere, enim nisl elementum','Steven Rosa',1989,'Rhythm and Blues',2),
    (9,'quis accumsan convallis, ante lectus convallis est, vitae','Richard Patel',1963,'Dance',1),
    (10,'at, libero. Morbi accumsan laoreet ipsum.','Seth Cantrell',1966,'Rock',3),
    (11,'ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque','Richard Mcleod',1972,'Soul',3),
    (12,'id, mollis nec, cursus a, enim.','Jack Dillon',1973,'Dance',4),
    (13,'sit amet ornare lectus justo eu','Kitra Soto',1965,'Country',3),
    (14,'mi. Duis risus odio, auctor vitae,','Keith Acevedo',1978,'Dance',3),
    (15,'Quisque varius. Nam porttitor scelerisque neque. Nullam','Magee Kline',1990,'Dance',3),
    (16,'pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper,','Martin Benson',1999,'Rock and Roll',4),
    (17,'ac orci. Ut semper pretium neque. Morbi quis urna. Nunc','Murphy Pugh',1991,'Hip-Hop',2),
    (18,'mi lacinia mattis. Integer eu lacus.','Erin Rojas',1965,'Rock',2),
    (19,'a, facilisis non, bibendum sed, est. Nunc','Alma Blake',1977,'Rock and Roll',3),
    (20,'libero. Proin mi. Aliquam gravida mauris','Macey Cook',1992,'Blues',3),
    (21,'eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla','Kelsey Norton',1967,'Blues',3),
    (22,'Duis volutpat nunc sit amet metus. Aliquam erat','Morgan Vinson',1994,'Blues',2),
    (23,'diam. Sed diam lorem, auctor quis, tristique ac, eleifend','Judah Rasmussen',1986,'Blues',1),
    (24,'diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent','Ciara Velasquez',1997,'Country',3),
    (25,'Fusce aliquet magna a neque. Nullam ut','Linda Manning',1977,'Rock',1),
    (26,'Praesent interdum ligula eu enim. Etiam imperdiet dictum','Gay Crane',1968,'Blues',4),
    (27,'ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis','Whoopi Barker',1988,'Blues',1),
    (28,'eleifend, nunc risus varius orci, in consequat enim','Ulla Bruce',1970,'Soul',4),
    (29,'Mauris magna. Duis dignissim tempor arcu. Vestibulum','Elijah Barrett',1984,'Jazz',2),
    (30,'montes, nascetur ridiculus mus. Proin vel arcu','Ian Townsend',1981,'Rock',3),
    (31,'ut mi. Duis risus odio, auctor vitae,','Sarah Navarro',1997,'Rock',1),
    (32,'Proin dolor. Nulla semper tellus id nunc interdum feugiat.','Caldwell Willis',1996,'Jazz',4),
    (33,'ante ipsum primis in faucibus orci luctus et ultrices posuere','Kyle Wooten',1971,'Hip-Hop',2),
    (34,'a nunc. In at pede. Cras vulputate velit eu sem.','Echo Hernandez',1963,'Hip-Hop',1),
    (35,'pellentesque a, facilisis non, bibendum sed, est.','Maite Bishop',1971,'Rock',3),
    (36,'sit amet, consectetuer adipiscing elit. Aliquam auctor,','Odysseus George',1986,'Rhythm and Blues',4),
    (37,'in, dolor. Fusce feugiat. Lorem ipsum dolor sit','Mary Andrews',1973,'Rhythm and Blues',3),
    (38,'amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,','Ferdinand Castillo',1997,'Hip-Hop',1),
    (39,'luctus, ipsum leo elementum sem, vitae aliquam eros turpis non','Lenore Wright',1995,'Rock',3),
    (40,'vestibulum. Mauris magna. Duis dignissim tempor','Quamar Holmes',1996,'Hip-Hop',1),
    (41,'In at pede. Cras vulputate velit eu sem.','Meghan Goodwin',1973,'Dance',3),
    (42,'In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.','Luke Kane',1974,'Rock',4),
    (43,'Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare','Macon Jones',1991,'Dance',4),
    (44,'ante lectus convallis est, vitae sodales nisi magna','Irene Chen',1978,'Blues',4),
    (45,'Mauris vestibulum, neque sed dictum eleifend, nunc risus','Zephania Page',1996,'Soul',1),
    (46,'elit sed consequat auctor, nunc nulla vulputate dui, nec tempus','Caleb Casey',1967,'Rhythm and Blues',2),
    (47,'Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo','Reuben Holman',1986,'Rock',2),
    (48,'venenatis vel, faucibus id, libero. Donec consectetuer','Bruno Carroll',1983,'Rock and Roll',2),
    (49,'feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem','Sydnee Trujillo',1993,'Dance',3),
    (50,'Curae Donec tincidunt. Donec vitae erat vel','Karleigh Miles',1999,'Dance',4),
    (51,'in sodales elit erat vitae risus. Duis a mi','Azalia Lynn',1994,'Rock',4),
    (52,'vel, mauris. Integer sem elit, pharetra ut,','Darrel Heath',1995,'Blues',1),
    (53,'Nullam enim. Sed nulla ante, iaculis nec, eleifend non,','Lynn Barry',1995,'Rock',2),
    (54,'augue. Sed molestie. Sed id risus quis','Upton Blanchard',1979,'Rhythm and Blues',2),
    (55,'lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis','Leah Santana',1995,'Hip-Hop',2),
    (56,'convallis, ante lectus convallis est, vitae','Ethan Patel',1985,'Country',3),
    (57,'mauris sapien, cursus in, hendrerit consectetuer, cursus','Fatima Wright',1980,'Jazz',1),
    (58,'rutrum non, hendrerit id, ante. Nunc mauris','Mechelle Pickett',1974,'Blues',4),
    (59,'ligula eu enim. Etiam imperdiet dictum magna. Ut','Elton Luna',1978,'Dance',4),
    (60,'quam. Curabitur vel lectus. Cum sociis natoque','Quail Nunez',1994,'Blues',3),
    (61,'cursus vestibulum. Mauris magna. Duis dignissim','Nehru Hewitt',1987,'Rock and Roll',2),
    (62,'quis, tristique ac, eleifend vitae, erat.','Ivor Patrick',1993,'Country',2),
    (63,'quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam','Kalia Riddle',1981,'Blues',3),
    (64,'non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit','Summer Whitney',1977,'Rock and Roll',3),
    (65,'vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae','Matthew Obrien',1997,'Soul',3),
    (66,'ac turpis egestas. Fusce aliquet magna','Cora Vasquez',1975,'Dance',3),
    (67,'nostra, per inceptos hymenaeos. Mauris ut quam vel sapien','Alec Moreno',1964,'Rhythm and Blues',2),
    (68,'elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et','Mason Maldonado',1977,'Rock and Roll',1),
    (69,'tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla','Tobias Burks',1979,'Hip-Hop',3),
    (70,'malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer','Adam Mccoy',1967,'Hip-Hop',3),
    (71,'tempor, est ac mattis semper, dui','Miranda Noel',1989,'Rhythm and Blues',2),
    (72,'Aliquam ornare, libero at auctor ullamcorper, nisl arcu','Leroy Mckenzie',1966,'Blues',2),
    (73,'magna. Nam ligula elit, pretium et, rutrum non, hendrerit id,','Kasper Stanton',1972,'Jazz',2),
    (74,'aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a,','Adara Randolph',1999,'Soul',1),
    (75,'blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci','Michael Nunez',1976,'Dance',1),
    (76,'in consequat enim diam vel arcu. Curabitur','Venus Shields',1992,'Hip-Hop',3),
    (77,'semper pretium neque. Morbi quis urna. Nunc quis','Autumn Schmidt',1998,'Hip-Hop',2),
    (78,'id, libero. Donec consectetuer mauris id sapien. Cras','Kane Moon',1990,'Country',1),
    (79,'nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam','Isaac Cruz',1964,'Rhythm and Blues',1),
    (80,'fringilla purus mauris a nunc. In at pede. Cras','Belle Everett',1970,'Soul',2),
    (81,'Lorem ipsum dolor sit amet, consectetuer adipiscing','Finn Atkins',1986,'Country',2),
    (82,'nonummy ipsum non arcu. Vivamus sit amet','Brady Moreno',1979,'Soul',1),
    (83,'id, libero. Donec consectetuer mauris id sapien. Cras dolor','Donna Bird',1986,'Rock',2),
    (84,'quis diam luctus lobortis. Class aptent','Mohammad Schneider',1963,'Jazz',3),
    (85,'enim. Etiam imperdiet dictum magna. Ut tincidunt orci','Zeus Odonnell',1971,'Dance',2),
    (86,'vel lectus. Cum sociis natoque penatibus et magnis dis parturient','Quyn Malone',1987,'Jazz',4),
    (87,'auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus,','Raphael Bell',1992,'Hip-Hop',4),
    (88,'est arcu ac orci. Ut semper','Coby Riley',1991,'Soul',1),
    (89,'at, nisi. Cum sociis natoque penatibus et magnis dis','Valentine Beasley',1976,'Country',1),
    (90,'aliquet. Phasellus fermentum convallis ligula. Donec','Quyn Graham',1988,'Country',2),
    (91,'lobortis mauris. Suspendisse aliquet molestie tellus.','Constance Cash',1978,'Dance',1),
    (92,'Duis volutpat nunc sit amet metus. Aliquam','Vladimir Hayes',1998,'Jazz',1),
    (93,'sit amet risus. Donec egestas. Aliquam nec enim. Nunc','Tashya Greer',1988,'Soul',4),
    (94,'nisi magna sed dui. Fusce aliquam, enim nec','Malik Singleton',1998,'Rhythm and Blues',3),
    (95,'Nullam ut nisi a odio semper cursus. Integer mollis. Integer','Dillon Huffman',1995,'Rhythm and Blues',3),
    (96,'semper pretium neque. Morbi quis urna. Nunc quis arcu','Oren Abbott',1963,'Rock and Roll',3),
    (97,'molestie. Sed id risus quis diam luctus','Orlando Dejesus',1989,'Country',3),
    (98,'felis eget varius ultrices, mauris ipsum porta elit,','Quinn Newman',1991,'Country',3),
    (99,'nulla at sem molestie sodales. Mauris blandit','Gretchen Blevins',1998,'Soul',4),
    (100,'sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet','Violet Graham',1999,'Dance',3);

